some updates to corereleasebranches

diff --git a/corereleasebranches/corereleasebranches b/corereleasebranches/corereleasebranches
--- a/corereleasebranches/corereleasebranches
+++ b/corereleasebranches/corereleasebranches
@@ -1,11 +1,65 @@
 #!/bin/bash
 
-REPO=`readlink -f $1`
+REPODIR=`readlink -f $1`
 
 OLDREPONAMES="artwork base bootstrap calc components extensions extras filters impress libs-core libs-extern-sys libs-extern libs-gui postprocess sdk testing ure writer" 
 
+BISECTFUNCTOR=`mktemp`
+chmod u+x $BISECTFUNCTOR
+cat > $BISECTFUNCTOR <<EOF
+#!/bin/bash
+for file in \`cd \$1 && find . -type f -not -path "./.git*"\`
+do
+    if [ -e \$file ]
+    then
+        if [ ! \$file -nt \$1/\$file ]
+        then
+            exit 1
+        fi
+    fi
+done
+exit 0
+EOF
+
+function recreate_repotag {
+    local REPO=$1
+    local TAGTOFIND=$2
+    local LOWERBOUND=$3
+    local UPPERBOUND=$4
+    if [ -n "`cd $REPODIR/core && git tag|grep ${REPO}_${TAGTOFIND}`" ]
+    then
+        echo "tag ${REPO}_${TAGTOFIND} exists already in core."
+        return
+    fi
+    if [ -z "`cd $REPODIR/$REPO && git tag|grep ${TAGTOFIND}`" ]
+    then
+        echo "tag ${TAGTOFIND} also missing in repo ${REPO}."
+        return
+    fi
+    echo "searching for $TAGTOFIND from $REPO between $LOWERBOUND and $UPPERBOUND"
+    pushd $REPODIR/core > /dev/null
+    #find the first commit with any file younger than in the reference
+    if [ "`git rev-list --no-walk ${REPO}_$LOWERBOUND`" = "`git rev-list --no-walk ${REPO}_${UPPERBOUND}`" ]
+    then
+        git tag ${REPO}_${TAGTOFIND} ${REPO}_$LOWERBOUND
+    else
+        `cd $REPODIR/$REPO && git checkout $TAGTOFIND`
+        git bisect reset
+        git bisect start ${REPO}_${UPPERBOUND} ${REPO}_${LOWERBOUND}^
+        git bisect run $BISECTFUNCTOR $REPODIR/$REPO
+        if [ "$?" -eq "0" ]
+        then
+            git tag ${REPO}_${TAGTOFIND} HEAD^
+        else
+            exit 1
+        fi
+        git bisect reset
+    fi
+    popd > /dev/null
+}
+
 function premerge_fixes {
-    pushd $REPO > /dev/null
+    pushd $REPODIR/core > /dev/null
     rm .git/hooks/*
     git tag writer_LIBREOFFICE_3_3_0_1 520eb9a251e557ffbebfc79deb5ee0cb55600d9e
     git tag postprocess_LIBREOFFICE_3_3_0_1 98bb7da5f26a1644397dbe73d35e0a083e45da85
@@ -13,14 +67,27 @@ function premerge_fixes {
     git tag -d filters_feature/gnumake4_writerfilter_head
     for repo in $OLDREPONAMES
     do
+        recreate_repotag ${repo} OOO_BUILD_3_2_98_1 OOO_BUILD_3_2_98_0 LIBREOFFICE_3_3_0_1
+        recreate_repotag ${repo} LIBREOFFICE_3_2_99_1 OOO_BUILD_3_2_98_1 LIBREOFFICE_3_3_0_1
+
+        recreate_repotag ${repo} libreoffice-3.3.1.2 libreoffice-3.3.0.3 libreoffice-3.3.2.1
+        recreate_repotag ${repo} libreoffice-3.3.0.4 libreoffice-3.3.0.3 libreoffice-3.3.1.2
+        recreate_repotag ${repo} libreoffice-3.3.1.1 libreoffice-3.3.0.4 libreoffice-3.3.1.2
+
+        recreate_repotag ${repo} libreoffice-3.3.3.1 libreoffice-3.3.1.2 libreoffice-3.4.0.1
+        recreate_repotag ${repo} libreoffice-3.3.4.1 libreoffice-3.3.3.1 libreoffice-3.4.0.1
+        recreate_repotag ${repo} libreoffice-3.3.2.2 libreoffice-3.3.2.1 libreoffice-3.3.3.1
+
         git tag -d ${repo}_ooo/DEV300_last_svn_milestone
     done
     popd > /dev/null
 }
 
 function postmerge_fixes {
-    pushd $REPO > /dev/null
+    pushd $REPODIR/core > /dev/null
     rm .git/hooks/*
+    git tag libreoffice-3.2.99.1 LIBREOFFICE_3_2_99_1
+    git tag -d LIBREOFFICE_3_2_99_1
     git tag libreoffice-3.2.99.2 LIBREOFFICE_3_2_99_2
     git tag -d LIBREOFFICE_3_2_99_2
     git tag libreoffice-3.2.99.3 LIBREOFFICE_3_2_99_3
@@ -41,7 +108,7 @@ function postmerge_fixes {
 
 function tag_to_notes {
     local TAG=$1
-    pushd $REPO > /dev/null
+    pushd $REPODIR/core > /dev/null
     local OLDREPOTAGS=`for repo in $OLDREPONAMES;do echo ${repo}_${TAG}; done`
     # -remove split repo tags
     # -write split repo notes replacing the tag
@@ -58,8 +125,13 @@ function tag_to_notes {
 }
 
 function merge_tag {
-    pushd $REPO > /dev/null
     local TAG=$1
+    # -dont try to create an existing tag
+    if [ -z "`git tag|grep ${TAG}`" ]
+    then
+        return
+    fi
+    pushd $REPODIR/core > /dev/null
     local OLDREPOTAGS=`for repo in $OLDREPONAMES;do echo ${repo}_${TAG}; done`
     # -check if all repo tags are there
     local MISSINGTAGS=
@@ -105,13 +177,13 @@ function create_branch {
     [ -n "$BRANCHNAME" ] || return
     [ -n "$TAGS" ] || return
     local BOOTSTRAPTAGS=""
-    pushd $REPO > /dev/null
+    pushd $REPODIR/core > /dev/null
     for tag in $TAGS
     do
         BOOTSTRAPTAGS="$BOOTSTRAPTAGS bootstrap_$tag"
     done
     #sort tags for this branch topological
-    local ORDEREDBOOTSTRAPHASHES=`cd $REPO && git rev-list --no-walk --topo-order --reverse $BOOTSTRAPTAGS`
+    local ORDEREDBOOTSTRAPHASHES=`git rev-list --no-walk --topo-order --reverse $BOOTSTRAPTAGS`
     local BRANCHCREATED=
     for hash in $ORDEREDBOOTSTRAPHASHES
     do
@@ -161,10 +233,9 @@ cat > $FINDREPOBRANCHES <<EOF
         TAGSFORBRANCH["ooo/DEV300_last_svn_milestone"] = "ooo/DEV300_m63";
         TAGSFORBRANCH["libreoffice-3-4-2"] = "libreoffice-3.4.1.1";
         TAGSFORBRANCH["libreoffice-3-4-1"] = "libreoffice-3.4.0.1";
-        # libreoffice-3.3 is way undertagged for now so we leave it out
-        #TAGSFORBRANCH["libreoffice-3-3-3"] = "libreoffice-3.3.2.1";
-        #TAGSFORBRANCH["libreoffice-3-3-2"] = "libreoffice-3.3.1.1";
-        #TAGSFORBRANCH["libreoffice-3-3-1"] = "LIBREOFFICE_3.3.1.1";
+        TAGSFORBRANCH["libreoffice-3-3-3"] = "libreoffice-3.3.2.1";
+        TAGSFORBRANCH["libreoffice-3-3-2"] = "libreoffice-3.3.1.1";
+        TAGSFORBRANCH["libreoffice-3-3-1"] = "LIBREOFFICE_3.3.1.1";
     }
     /^libreoffice-.*/ {
         MAJOR=\$1 "-" \$2
@@ -173,8 +244,6 @@ cat > $FINDREPOBRANCHES <<EOF
         # libreoffice-3.3 is way undertagged for now so we leave it out
         # we can make a run for it later, when there are enough tags
         # (or at least the release finals)
-        if(\$2=="3")
-            next;
         if(\$4=="1")
             TAGSFORBRANCH[MAJOR] = TAGSFORBRANCH[MAJOR] " " RC;
         TAGSFORBRANCH[MINOR] = TAGSFORBRANCH[MINOR] " " RC;
@@ -214,7 +283,7 @@ EOF
 premerge_fixes
 ALLMISSINGTAGS=
 SKIPPEDTAGS=
-SPLITREPOTAGS=`cd $REPO; git tag|grep bootstrap|sed s/^bootstrap_//`
+SPLITREPOTAGS=`cd $REPODIR/core; git tag|grep bootstrap|sed s/^bootstrap_//`
 echo $SPLITREPOTAGS|awk -f $FINDREPOBRANCHES > $TAGSFORBRANCH
 cat $TAGSFORBRANCH
 echo "SPLITREPOTAGS: $SPLITREPOTAGS"
@@ -223,7 +292,7 @@ for TAG in $SPLITREPOTAGS
 do
     tag_to_notes $TAG
 done
-rm $FINDREPOBRANCHES $TAGSFORBRANCH
+rm $FINDREPOBRANCHES $TAGSFORBRANCH $BISECTFUNCTOR
 postmerge_fixes
 echo "Missing tags: $ALLMISSINGTAGS"
 echo "Skipped tags: $SKIPPEDTAGS"
